/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ivan Norman (https://sketchfab.com/vanidza)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-truck-car-drifter-f3750246b6564607afbefc61cb1683b1
Title: Low-poly truck (car "Drifter")
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import jeepScene from '../components/jeep.glb'

const Jeep = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(jeepScene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="7f09d404031140d78a7bb6db74b81fa4fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Front_wheel"
                  position={[155.6, 9.3, -127.3]}
                  rotation={[0, 0, -1.4]}
                  scale={[50.1, 50.1, 27]}>
                  <mesh
                    name="Front_wheel_Black_0"
                    geometry={nodes.Front_wheel_Black_0.geometry}
                    material={materials.Black}
                  />
                  <mesh
                    name="Front_wheel_Light_black_0"
                    geometry={nodes.Front_wheel_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                </group>
                <group
                  name="Rear_wheel"
                  position={[-128.5, 14.3, -126]}
                  rotation={[0, 0, -2.2]}
                  scale={[55.1, 55.1, 29.6]}>
                  <mesh
                    name="Rear_wheel_Black_0"
                    geometry={nodes.Rear_wheel_Black_0.geometry}
                    material={materials.Black}
                  />
                  <mesh
                    name="Rear_wheel_Light_black_0"
                    geometry={nodes.Rear_wheel_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                </group>
                <group
                  name="Front_wheel001"
                  position={[155.6, 9.3, 127.3]}
                  rotation={[Math.PI, 0, 1.3]}
                  scale={[50.1, 50.1, 27]}>
                  <mesh
                    name="Front_wheel001_Black_0"
                    geometry={nodes.Front_wheel001_Black_0.geometry}
                    material={materials.Black}
                  />
                  <mesh
                    name="Front_wheel001_Light_black_0"
                    geometry={nodes.Front_wheel001_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                </group>
                <group
                  name="Rear_wheel001"
                  position={[-128.5, 14.3, 126]}
                  rotation={[Math.PI, 0, 2.1]}
                  scale={[55.1, 55.1, 29.6]}>
                  <mesh
                    name="Rear_wheel001_Black_0"
                    geometry={nodes.Rear_wheel001_Black_0.geometry}
                    material={materials.Black}
                  />
                  <mesh
                    name="Rear_wheel001_Light_black_0"
                    geometry={nodes.Rear_wheel001_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                </group>
                <group
                  name="Spring"
                  position={[155.6, 20.7, -82]}
                  rotation={[-0.2, Math.PI / 2, 0]}
                  scale={2.8}>
                  <mesh
                    name="Spring_Light_black_0"
                    geometry={nodes.Spring_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                  <mesh
                    name="Spring_Black_0"
                    geometry={nodes.Spring_Black_0.geometry}
                    material={materials.Black}
                  />
                </group>
                <group
                  name="Spring001"
                  position={[-128.5, 20.7, -82]}
                  rotation={[-0.2, Math.PI / 2, 0]}
                  scale={2.8}>
                  <mesh
                    name="Spring001_Light_black_0"
                    geometry={nodes.Spring001_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                  <mesh
                    name="Spring001_Black_0"
                    geometry={nodes.Spring001_Black_0.geometry}
                    material={materials.Black}
                  />
                </group>
                <group
                  name="Spring002"
                  position={[155.6, 20.7, 82]}
                  rotation={[0.2, -Math.PI / 2, 0]}
                  scale={2.8}>
                  <mesh
                    name="Spring002_Light_black_0"
                    geometry={nodes.Spring002_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                  <mesh
                    name="Spring002_Black_0"
                    geometry={nodes.Spring002_Black_0.geometry}
                    material={materials.Black}
                  />
                </group>
                <group
                  name="Spring003"
                  position={[-128.5, 20.7, 82]}
                  rotation={[0.2, -Math.PI / 2, 0]}
                  scale={2.8}>
                  <mesh
                    name="Spring003_Light_black_0"
                    geometry={nodes.Spring003_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                  <mesh
                    name="Spring003_Black_0"
                    geometry={nodes.Spring003_Black_0.geometry}
                    material={materials.Black}
                  />
                </group>
                <group name="Smoke001" position={[70.4, 165.3, 94.3]} scale={0}>
                  <mesh
                    name="Smoke001_Smoke_0"
                    geometry={nodes.Smoke001_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke002" position={[74.6, 165.7, 92.4]} scale={0}>
                  <mesh
                    name="Smoke002_Smoke_0"
                    geometry={nodes.Smoke002_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke003" position={[72.2, 166.5, 95.1]} scale={0}>
                  <mesh
                    name="Smoke003_Smoke_0"
                    geometry={nodes.Smoke003_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke004" position={[73.1, 165.6, 93.1]} scale={0}>
                  <mesh
                    name="Smoke004_Smoke_0"
                    geometry={nodes.Smoke004_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke005" position={[75.2, 166, 95.2]} scale={0}>
                  <mesh
                    name="Smoke005_Smoke_0"
                    geometry={nodes.Smoke005_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke006" position={[75.9, 167.4, 89.9]} scale={0}>
                  <mesh
                    name="Smoke006_Smoke_0"
                    geometry={nodes.Smoke006_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke007" position={[75, 167.9, 90.9]} scale={0}>
                  <mesh
                    name="Smoke007_Smoke_0"
                    geometry={nodes.Smoke007_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke008" position={[73.6, 166.4, 94.5]} scale={0}>
                  <mesh
                    name="Smoke008_Smoke_0"
                    geometry={nodes.Smoke008_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke009" position={[70.8, 159.6, 95.1]} scale={0}>
                  <mesh
                    name="Smoke009_Smoke_0"
                    geometry={nodes.Smoke009_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke010" position={[72.9, 163.5, 93]} scale={0}>
                  <mesh
                    name="Smoke010_Smoke_0"
                    geometry={nodes.Smoke010_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke011" position={[75, 162.6, 91.6]} scale={0}>
                  <mesh
                    name="Smoke011_Smoke_0"
                    geometry={nodes.Smoke011_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Smoke012" position={[73.8, 161.8, 89.9]} scale={0}>
                  <mesh
                    name="Smoke012_Smoke_0"
                    geometry={nodes.Smoke012_Smoke_0.geometry}
                    material={materials.Smoke}
                  />
                </group>
                <group name="Frame" rotation={[-Math.PI / 2, 0, 0]} scale={[300, 100, 50]}>
                  <mesh
                    name="Frame_Orange_0"
                    geometry={nodes.Frame_Orange_0.geometry}
                    material={materials.Orange}
                  />
                  <mesh
                    name="Frame_Black_0"
                    geometry={nodes.Frame_Black_0.geometry}
                    material={materials.Black}
                  />
                  <mesh
                    name="Frame_Glass_0"
                    geometry={nodes.Frame_Glass_0.geometry}
                    material={materials.Glass}
                  />
                  <mesh
                    name="Frame_Light_0"
                    geometry={nodes.Frame_Light_0.geometry}
                    material={materials.Light}
                  />
                  <mesh
                    name="Frame_Light_red_0"
                    geometry={nodes.Frame_Light_red_0.geometry}
                    material={materials.Light_red}
                  />
                  <mesh
                    name="Frame_Dark_brown_0"
                    geometry={nodes.Frame_Dark_brown_0.geometry}
                    material={materials.Dark_brown}
                  />
                  <mesh
                    name="Frame_Dark_brown_handle_0"
                    geometry={nodes.Frame_Dark_brown_handle_0.geometry}
                    material={materials.Dark_brown_handle}
                  />
                  <mesh
                    name="Frame_Glass_trailer_0"
                    geometry={nodes.Frame_Glass_trailer_0.geometry}
                    material={materials.Glass_trailer}
                  />
                  <mesh
                    name="Frame_Light_black_0"
                    geometry={nodes.Frame_Light_black_0.geometry}
                    material={materials.Light_black}
                  />
                  <mesh
                    name="Frame_Brown_0"
                    geometry={nodes.Frame_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Jeep